# Sample repository at https://github.com/Novfensec/SAMPLE-KIVYMD-APP
# Tic Tac Toe Game at https://github.com/Novfensec/Tic-Tac-Toe-Android

name: Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      # Used to cache dependencies with a timeout
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(date -u '+%Y%m%d')" >> $GITHUB_ENV
        shell: bash

      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: ~/.buildozer
          key: buildozer-global-${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            buildozer-global-${{ runner.os }}-

      - name: Cache Buildozer directory in app
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-buildozer-${{ github.run_id }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      - name: Cache Android SDK
        uses: actions/cache@v4
        with:
          path: ~/.buildozer/android/platform/android-sdk
          key: ${{ runner.os }}-android-sdk-${{ steps.get-date.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-android-sdk-

      - name: Cache Android NDK
        uses: actions/cache@v4
        with:
          path: ~/.buildozer/android/platform/android-ndk-r25b
          key: ${{ runner.os }}-android-ndk-${{ steps.get-date.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-android-ndk-

      # Install dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install -y \
            build-essential \
            git \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            libunwind-dev \
            zlib1g-dev
          sudo apt-get install -y \
            libsqlite3-dev \
            sqlite3 \
            bzip2 \
            libbz2-dev \
            zlib1g-dev \
            openssl \
            libgdbm-dev \
            libgdbm-compat-dev \
            liblzma-dev \
            libreadline-dev \
            uuid-dev \
            libgstreamer1.0 \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good
          sudo apt-get install -y \
            zip \
            unzip \
            autoconf \
            libtool \
            pkg-config \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo5 \
            cmake \
            libffi-dev \
            libssl-dev \
            automake

      # Set up Java 17 required by Gradle
      - name: Setup Java 17 required by Gradle
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # or 'zulu', 'liberica', etc.
          java-version: '17'

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' #set your python version

      # Install pip dependencies
      - name: Install pip dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.33 git+https://github.com/kivy/plyer.git

      # Build with Buildozer
      - name: Build with Buildozer
        id: buildozer
        run: |
          yes | buildozer -v android debug
        # yes | buildozer -v android release
        # run this for generating aab (Android App Bundle) [Required by google play]

      # Upload artifacts
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: |
            bin/*.apk
            bin/*.aab
          retention-days: 3
          Description:
In github actions, we install python, then use pipenv to install dependencies. The steps are as follows:

`jobs:
test:
name: Run Tests
runs-on: ubuntu-latest

steps:

- name: Check out repository code
  uses: actions/checkout@v4

- name: Setup Python
  uses: actions/setup-python@v5
  with:
    python-version: "3.11.11"

- name: Install pipenv
  run: |
    python -m pip install --upgrade pipenv wheel


- uses: actions/cache@v4
  id: pipenv-cache
  with:
    path: ~/.local/share/virtualenvs
    key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
    restore-keys: |
      ${{ runner.os }}-pipenv-

- name: Install dependencies
  if: steps.cache-pipenv.outputs.cache-hit != 'true'
  run: |
    pipenv install --deploy --dev
    pipenv install -e .
`

After upgrading the patch version from 3.11.10 to 3.11.11 we get the following error on the Install dependencies step:

Run pipenv install --deploy --dev Installing dependencies from Pipfile.lock (a990db)... Traceback (most recent call last): File "/opt/hostedtoolcache/Python/3.11.11/x64/bin/pipenv", line 8, in <module> sys.exit(cli()) ^^^^^ File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1157, in __call__ return self.main(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/pipenv/cli/options.py", line 52, in main return super().main(*args, **kwargs, windows_expand_args=False) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1078, in main rv = self.invoke(ctx) ^^^^^^^^^^^^^^^^ File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 1688, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line [14](https://github.com/argoXai/echion/actions/runs/12298597226/job/34370725919#step:6:15)34, in invoke return ctx.invoke(self.callback, **ctx.params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 783, in invoke return __callback(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/pipenv/vendor/click/decorators.py", line 92, in new_func return ctx.invoke(f, obj, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/pipenv/vendor/click/core.py", line 783, in invoke return __callback(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/pipenv/cli/command.py", line 207, in install do_install( File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/pipenv/routines/install.py", line 341, in do_install raise e File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/pipenv/routines/install.py", line 327, in do_install do_install_dependencies( File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/pipenv/routines/install.py", line 530, in do_install_dependencies batch_install( File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/pipenv/routines/install.py", line 595, in batch_install deps_to_install = [ ^ File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/pipenv/routines/install.py", line 598, in <listcomp> if not project.environment.is_satisfied(dep) ^^^^^^^^^^^^^^^^^^^ File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/pipenv/project.py", line 508, in environment self._environment = self.get_environment(allow_global=allow_global) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/pipenv/project.py", line 494, in get_environment environment = Environment( ^^^^^^^^^^^^ File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/pipenv/environment.py", line 81, in __init__ self._base_paths = self.get_paths() ^^^^^^^^^^^^^^^^ File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/pipenv/environment.py", line 342, in get_paths c = subprocess_run(command) ^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/pipenv/utils/processes.py", line 72, in subprocess_run return subprocess.run( ^^^^^^^^^^^^^^^ File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/subprocess.py", line 548, in run with Popen(*popenargs, **kwargs) as process: ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/subprocess.py", line 1026, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/subprocess.py", line [19](https://github.com/argoXai/echion/actions/runs/12298597226/job/34370725919#step:6:20)55, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/.local/share/virtualenvs/echion-h5L6Iya-/bin/python' Error: Process completed with exit code 1.

Action version:
Specify the action version

Platform:
Current runner version: '2.321.0'
Operating System
Ubuntu
22.04.5
LTS
Runner Image
Image: ubuntu-22.04
Version: 20241201.1.0
Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20241201.1/images/ubuntu/Ubuntu2204-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20241201.1
Runner Image Provisioner
2.0.385.1

Runner type:

Hosted
Tools version:
Python 3.10.10 -> 3.10.11

Repro steps:
Create a repo with a Pipfile.lock file at root, and a github actions file with the steps above, and push to run github actions on Python 3.10.11 .

Expected behavior:
Python deps install correctly

Actual behavior:
We get the error above
